# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' rcpp_hello
#' @description
#' This is a simple function using Rcpp that creates an R list containing a
#' character vector and a numeric vector.
#'
#' @details
#' Not much to report.
#'
#' @return
#' a list with a character vector and a numeric vector
#'
#' @useDynLib slalom
#' @importFrom Rcpp evalCpp
#' @export
#' @examples
#' rcpp_hello()
rcpp_hello <- function() {
    .Call('slalom_rcpp_hello', PACKAGE = 'slalom')
}

