# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' SlalomModel C++ class
#' @description
#' A C++ class for SlalomModel models.
#'
#' @param Y_init matrix of expression values
#' @param pi_init G x K matrix with each entry being the prior
#' probability for a gene g being active for factor k.
#' @param X_init matrix of initial factor states (N x K)
#' @param W_init G x K matrix of initial weights
#' @param prior_alpha numeric vector of length two giving prior values
#' for the gamma hyperparameters of the precisions
#' @param prior_epsilon numeric vector of length two giving prior values
#' for the gamma hyperparameters of the residual variances
#'
#' @return
#' an object of the SlalomModel class
#'
#' @useDynLib slalom
#' @importFrom Rcpp evalCpp
#' @exportClass Rcpp_SlalomModel
NULL

